---CONSULTA TABELA DE CLIENTES---
SELECT * FROM cliente;

---CONSULTA DE COLUNA DA TABELA DE ITENS PEDIDOS ESPECÍFICA--
SELECT id_itempedido,quantidade,preco_unitario FROM itempedido;

---CONSULTA COM FILTRO DE PREÇOS DA TABELA PRODUTO---
SELECT * FROM produto
WHERE preco > 4.00;

---LIMITAR RESULTADOS PARA CONSULTA---
SELECT * FROM pagamento
LIMIT 3;
 
---CONSULTAR VALORES UNICOS DAS CATEGORIAS---
SELECT DISTINCT nome,funcao FROM funcionario;

---CONSULTA DE QUAIS CARTOÊS TENHO NA FORMA DE PAGAMENTO---
SELECT * FROM pagamento
WHERE forma_pagamento LIKE 'cartão %';